### ISSUE TITLE
Wonder Boy III - Monster Lair (set 6, World, System 16B) (8751 317-0098) - no sound

### ISSUE THREAD

**Issue by tjanas** [jotego/jts16#2]
As referenced here:
https://misterfpga.org/viewtopic.php?f=25&t=4323&sid=ed6f05eb135b75617d69bd863ded6002

When using 'Wonder Boy III - Monster Lair (set 6, World, System 16B) (8751 317-0098).mra' downloaded with [update_all](https://github.com/theypsilon/Update_All_MiSTer), there is no sound. However, there _is_ sound when using any of the mra's in `_Arcade/_alternatives/_Wonder Boy III/`.

**Comment by jotego** [comment]
There is no dump for the MCU ROM in that game. That's why there is no sound. MAME emulates the MCU behaviour without a ROM. I wrote my own ROM for it. So the game in MiSTer uses the full hardware setup as the original, even though the MCU is running a different code.

Copy this file to the games/mame folder.

[s16mcu_alt.zip](https://github.com/jotego/jts16/files/8240547/s16mcu_alt.zip)

In case you are curious, the source code is [here](https://github.com/jotego/jts16/blob/master/firmware/wb3.s).
 
Please kindly reply in the forum about this. Feel free to distribute the homebrew MCU ROM I made. Consider supporting this project too, please.

**Comment by tjanas** [comment]
I copied that zip to my games/mame directory and did a cold reboot, but I still am not getting any sound.

**Comment by jotego** [comment]
Mmm, you're right. The published MRA does not try to load the homebrew ROM. I may just delete this MRA file as it's very troublesome because of the missing ROM.

**Comment by jotego** [comment]
@atrac17 could you try modifying the MRA file to read the MCU homebrew file as we did during the beta phase? Then, after you have it working, could you modify further the MRA to have the hexadecimal dump of the MCU file directly in the MRA file? As it is my own code, there is no copyright problem in having the contents directly there.

**Comment by jotego** [comment]
I have deleted this MRA in JTBIN. I'm fed up of people complaining about it. WB3 set 6 is now the main MRA"
